### PR TITLE
Add yapf style file

### PR DESCRIPTION
**Pull request by Laura7089**
Adds a [`yapf`](https://github.com/google/yapf) style guide file so that we can have consistent formatting across the codebase.

Right now, I've only added the style file so that we can play around with it and fiddle with the options - checkout the branch, `cd` into the root directory, then run `yapf -i filename.py` on your favourite code and see what you think.

### CODE REVIEW

**Comment by Laura7089** [comment]
Once we've settled on a style everyone's happy with, we can run this on the base files and possibly leave the cogs until no one's actively working on them since formatting changes produce enormous merge conflicts...

**Comment by Laura7089** [comment]
Added line ending normalisation since we should probably control that too. See https://www.git-scm.com/docs/gitattributes for how this is accomplished; if I'm reading those docs correctly, we'd still need to run a tool like `dos2unix` over the whole repo.

**Comment by Trimatix** [comment]
Important to mention that for line ending normalization to work, we should use `--renormalize` on every `git add`

normalization can be changed on a per-filetype basis as in https://github.com/benslv/countable/blob/master/.gitattributes if needed

**Comment by Laura7089** [comment]
> Important to mention that for line ending normalization to work, we should use --renormalize on every git add

If we run a tool over the repo to fix line endings as they are, editors should respect that and we won't need this.

**Comment by Trimatix** [comment]
that would make sense... I'm no expert but I thought it only renormalized the files you had staged 🤔

**Comment by Trimatix** [comment]
Meeting notes:
- use one line per formal parameter in function definitions
- use one line per dictionary entry
- 127/8 char line lengths
- De-dent closing brackets

**Review by Luceapuce — APPROVED** [review]

**Pull request merged**
