### PR TITLE
Altered directory name and entrypoint

### PR DESCRIPTION
**Pull request by Ryth-cs**

### CODE REVIEW

**Comment by Laura7089** [comment]
You've got a dangling commit here

**Comment by Laura7089** [comment]
See #143. I'd really rather we don't run with `/` as the working directory within the container, I prefer to adjust the import path of the strings file.

**Comment by Ryth-cs** [comment]
> You've got a dangling commit here

Yeah, I made the branch off the previous one by mistake. It shouldn't be an issue though if we merge though right?

**Comment by Ryth-cs** [comment]
> See #143. I'd really rather we don't run with `/` as the working directory within the container, I prefer to adjust the import path of the strings file.

Benji and I looked at this as it causes an issue for running locally or Docker. Altering the Docker container like this was the most logical solution we could come up with.

**Comment by Laura7089** [comment]
We can move everything inside `src` into the root folder to fix this

**Comment by Ryth-cs** [comment]
> We can move everything inside `src` into the root folder to fix this, just tested and it works fine on my local

Yeah, we can do that if you think it's best. We were just trying to avoid any major changes

**Comment by Laura7089** [comment]
I can update my PR but it will break the existing ones. We need to get those merged. Closing this one.

**Pull request closed without merging**
