### PR TITLE
Fix user_strings.toml path to not reference top-level directory

### PR DESCRIPTION
**Pull request by Laura7089**

### CODE REVIEW

**Review by Fluxticks — APPROVED** [review]
Just need to tell the load_dotenv function the name of the secrets file as it won't automatically pick it up now

**Comment by Laura7089** [comment]
> 
> 
> Just need to tell the load_dotenv function the name of the secrets file as it won't automatically pick it up now

I added the `source` line to the readme, which serves the same purpose. Does the function actually support using different filenames? Also, the function will do nothing in docker. Perhaps worth removing?

**Comment by Fluxticks** [comment]
In docker yes but is needed for people like me who run it outside of docker

**Comment by Laura7089** [comment]
Added the path correction to the function call.

**Review by Fluxticks — APPROVED** [review]

**Pull request merged**
